# This config file renders the "primer-spec" theme from:
# https://eecs485staff.github.io/primer-spec/docs/USAGE_ADVANCED.html#site-configuration-options
# This theme is built on the default GitHub Markdown theme "Primer", and
# optionally renders a sidebar to easily navigate project specs.

title: "EECS 280 Tutorials"

favicon: https://eecs280staff.github.io/eecs280.org/assets/images/eecs280favicon.ico

remote_theme: eecs485staff/primer-spec
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-default-layout
  - jemoji
kramdown:
  input: GFM
readme_index:
  remove_originals: true
  with_frontmatter: true
